import { SignJWT } from "jose";
import crypto from "node:crypto";
import type { JwtKeyRegistry } from "./jwt-keys.js";

// Minimal access-token claims per V4 claims-minimization rule.
// NO email, NO login, NO PII -- only role-IDs + timing.
export interface AccessTokenClaims {
  sub: string; // user_id
  active_org_id: string;
  family_id: string; // for refresh-token reuse detection
  role: "admin" | "member" | "service";
  service_account?: boolean; // present on service tokens (T25)
  scope?: "read" | "write" | "admin"; // present on service tokens
  issued_by?: string; // present on service tokens (admin user_id)
}

export interface MintAccessJWTOptions {
  claims: AccessTokenClaims;
  registry: JwtKeyRegistry;
  issuer: string; // COORDINATOR_PUBLIC_URL
  ttlSeconds: number; // from getOrgSetting("jwt_access_ttl") -- T44; default 900 (15 min)
}

// Mint a signed access JWT. HS256 pinned, kid in header. Pure function.
export async function mintAccessJWT(opts: MintAccessJWTOptions): Promise<string> {
  const jti = crypto.randomUUID();
  return new SignJWT({ ...opts.claims, jti })
    .setProtectedHeader({ alg: "HS256", kid: opts.registry.current.kid })
    .setIssuer(opts.issuer)
    .setIssuedAt()
    .setExpirationTime(`${opts.ttlSeconds}s`)
    .setJti(jti)
    .sign(opts.registry.current.key);
}

// Minimal refresh-token claims.
export interface RefreshTokenClaims {
  sub: string;
  active_org_id: string;
  family_id: string;
  parent_jti?: string; // null for family root; jti of predecessor otherwise
}

export interface MintRefreshJWTOptions {
  claims: RefreshTokenClaims;
  registry: JwtKeyRegistry;
  issuer: string;
  ttlSeconds: number; // default 30*86400 (30 days)
  jti?: string; // optionally pre-generated by caller for atomic INSERT (T19a)
}

export interface MintedRefreshJWT {
  jwt: string;
  jti: string;
}

export async function mintRefreshJWT(
  opts: MintRefreshJWTOptions,
): Promise<MintedRefreshJWT> {
  const jti = opts.jti ?? crypto.randomUUID();
  const jwt = await new SignJWT({ ...opts.claims, jti })
    .setProtectedHeader({ alg: "HS256", kid: opts.registry.current.kid })
    .setIssuer(opts.issuer)
    .setIssuedAt()
    .setExpirationTime(`${opts.ttlSeconds}s`)
    .setJti(jti)
    .sign(opts.registry.current.key);
  return { jwt, jti };
}
