import { SignJWT } from "jose";
import crypto from "node:crypto";
import type { JwtKeyRegistry } from "./jwt-keys.js";

// Minimal access-token claims per V4 claims-minimization rule.
// NO email, NO login, NO PII -- only role-IDs + timing.
export interface AccessTokenClaims {
  sub: string; // user_id
  active_org_id: string;
  family_id: string; // for refresh-token reuse detection
  role: "admin" | "member" | "service";
  service_account?: boolean; // present on service tokens (T25)
  scope?: "read" | "write" | "admin"; // present on service tokens
  issued_by?: string; // present on service tokens (admin user_id)
}

export interface MintAccessJWTOptions {
  claims: AccessTokenClaims;
  registry: JwtKeyRegistry;
  issuer: string; // COORDINATOR_PUBLIC_URL
  ttlSeconds: number; // from getOrgSetting("jwt_access_ttl") -- T44; default 900 (15 min)
  /**
   * Optional Unix-seconds timestamp to pin `iat`. Used by T19b deterministic
   * re-mint within the 10s rotation grace window so a retried request returns
   * a byte-identical JWT (per V3 §B-NEW-2). Omit for normal mints (default
   * `setIssuedAt()` -> current time).
   */
  iatOverride?: number;
  /**
   * Optional pre-generated jti. Used by T19b deterministic re-mint to
   * preserve the successor's jti across grace-window retries.
   */
  jti?: string;
}

// Mint a signed access JWT. HS256 pinned, kid in header. Pure function.
export async function mintAccessJWT(opts: MintAccessJWTOptions): Promise<string> {
  const jti = opts.jti ?? crypto.randomUUID();
  // securite-auth-01: mark this JWT as an access token so verifiers can
  // reject a stolen/misrouted refresh token presented as a session/Bearer
  // credential (token-type confusion).
  const builder = new SignJWT({ ...opts.claims, typ: "access" })
    .setProtectedHeader({ alg: "HS256", kid: opts.registry.current.kid })
    .setIssuer(opts.issuer)
    .setJti(jti);
  if (opts.iatOverride !== undefined) {
    // Pin both iat AND exp to make the JWT byte-identical across retries.
    // jose's `setExpirationTime("Xs")` resolves against current wall clock;
    // we want it resolved against the pinned iat instead.
    builder.setIssuedAt(opts.iatOverride);
    builder.setExpirationTime(opts.iatOverride + opts.ttlSeconds);
  } else {
    builder.setIssuedAt();
    builder.setExpirationTime(`${opts.ttlSeconds}s`);
  }
  return builder.sign(opts.registry.current.key);
}

// Minimal refresh-token claims.
export interface RefreshTokenClaims {
  sub: string;
  active_org_id: string;
  family_id: string;
  parent_jti?: string; // null for family root; jti of predecessor otherwise
}

export interface MintRefreshJWTOptions {
  claims: RefreshTokenClaims;
  registry: JwtKeyRegistry;
  issuer: string;
  ttlSeconds: number; // default 30*86400 (30 days)
  jti?: string; // optionally pre-generated by caller for atomic INSERT (T19a)
  /**
   * Optional Unix-seconds timestamp to pin `iat`. Mirrors mintAccessJWT.
   * Used by T19b deterministic re-mint within the 10s rotation grace
   * window so a retried refresh request returns a byte-identical JWT.
   */
  iatOverride?: number;
}

export interface MintedRefreshJWT {
  jwt: string;
  jti: string;
}

export async function mintRefreshJWT(opts: MintRefreshJWTOptions): Promise<MintedRefreshJWT> {
  const jti = opts.jti ?? crypto.randomUUID();
  // securite-auth-01: mark this JWT as a refresh token so verifiers can
  // reject it if presented at an access-token consumer (session cookie /
  // Bearer) instead of the refresh-rotation endpoint.
  const builder = new SignJWT({ ...opts.claims, typ: "refresh" })
    .setProtectedHeader({ alg: "HS256", kid: opts.registry.current.kid })
    .setIssuer(opts.issuer)
    .setJti(jti);
  if (opts.iatOverride !== undefined) {
    builder.setIssuedAt(opts.iatOverride);
    builder.setExpirationTime(opts.iatOverride + opts.ttlSeconds);
  } else {
    builder.setIssuedAt();
    builder.setExpirationTime(`${opts.ttlSeconds}s`);
  }
  const jwt = await builder.sign(opts.registry.current.key);
  return { jwt, jti };
}
